# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

require_relative '../dotEngineSDKVersion'

target 'one-to-one' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for one-to-one
  #
  pod 'DotEngine', dotEngineSDKVersion
end
